-- raw_ozon.report_return_commision_02_lk source

CREATE OR REPLACE VIEW public._02_lk
AS WITH pre_fbo AS (
         SELECT fbo_list.client_id,
            fbo_list.load_dttm,
            fbo_list.order_id,
            fbo_list.order_number,
            fbo_list.posting_number,
            fbo_list.status,
            fbo_list.cancel_reason_id,
            fbo_list.created_at,
            fbo_list.in_process_at,
            fbo_list.sku,
            fbo_list.quantity,
            fbo_list.offer_id,
            fbo_list.name,
            fbo_list.currency_code,
            fbo_list.region,
            fbo_list.city,
            fbo_list.delivery_type,
            fbo_list.is_premium,
            fbo_list.payment_type_group_name,
            fbo_list.warehouse_id,
            fbo_list.warehouse_name,
            fbo_list.is_legal,
            fbo_list.commission_amount,
            fbo_list.commission_percent,
            fbo_list.payout,
            fbo_list.product_id,
            fbo_list.old_price,
            fbo_list.price,
            fbo_list.total_discount_value,
            fbo_list.total_discount_percent,
            fbo_list.actions,
            fbo_list.picking,
            fbo_list.client_price,
            fbo_list.cluster_from,
            fbo_list.cluster_to,
            row_number() OVER (PARTITION BY fbo_list.posting_number ORDER BY fbo_list.load_dttm DESC) AS rn
           FROM raw_ozon.fbo_list
        ), pre_fbs AS (
         SELECT fbs_list.client_id,
            fbs_list.load_dttm,
            fbs_list.posting_number,
            fbs_list.order_id,
            fbs_list.order_number,
            fbs_list.status,
            fbs_list.tracking_number,
            fbs_list.tpl_integration_type,
            fbs_list.in_process_at,
            fbs_list.shipment_date,
            fbs_list.delivering_date,
            fbs_list.customer_name,
            fbs_list.customer_pohone,
            fbs_list.upper_barcode,
            fbs_list.lower_barcode,
            fbs_list.is_express,
            fbs_list.parent_posting_number,
            fbs_list.available_actions,
            fbs_list.multi_box_qty,
            fbs_list.is_multibox,
            fbs_list.substatus,
            fbs_list.prr_option,
            fbs_list.quantum_id,
            fbs_list.id,
            fbs_list.delivery_date_begin,
            fbs_list.delivery_date_end,
            fbs_list.cancel_reason_id,
            fbs_list.cancel_reason,
            fbs_list.cancellation_type,
            fbs_list.cancelled_after_ship,
            fbs_list.affect_cancellation_rating,
            fbs_list.cancellation_initiator,
            fbs_list.offer_id,
            fbs_list.name,
            fbs_list.sku,
            fbs_list.mandatory_mark,
            fbs_list.region,
            fbs_list.city,
            fbs_list.delivery_type,
            fbs_list.is_premium,
            fbs_list.payment_type_group_name,
            fbs_list.warehouse_id,
            fbs_list.warehouse,
            fbs_list.tpl_provider_id,
            fbs_list.tpl_provider,
            fbs_list.delivering_date_begin,
            fbs_list.delivering_date_end,
            fbs_list.is_legal,
            fbs_list.commission_amount,
            fbs_list.commission_percent,
            fbs_list.payout,
            fbs_list.product_id,
            fbs_list.old_price,
            fbs_list.price,
            fbs_list.total_discount_value,
            fbs_list.total_discount_percent,
            fbs_list.actions,
            fbs_list.picking,
            fbs_list.quantity,
            fbs_list.currency_code,
            fbs_list.marketplace_service_item_fulfillment,
            fbs_list.marketplace_service_item_pickup,
            fbs_list.marketplace_service_item_dropoff_pvz,
            fbs_list.marketplace_service_item_dropoff_sc,
            fbs_list.marketplace_service_item_dropoff_ff,
            fbs_list.marketplace_service_item_direct_flow_trans,
            fbs_list.marketplace_service_item_return_flow_trans,
            fbs_list.marketplace_service_item_deliv_to_customev,
            fbs_list.marketplace_service_item_return_not_deliv_to_customer,
            fbs_list.marketplace_service_item_return_part_goods_customer,
            fbs_list.marketplace_service_item_return_after_deliv_to_customer,
            fbs_list.cluster_from,
            fbs_list.cluster_to,
            fbs_list.current_tariff_rate,
            fbs_list.current_tariff_type,
            fbs_list.current_tariff_charge,
            fbs_list.current_tariff_charge_currency_code,
            fbs_list.next_tariff_rate,
            fbs_list.next_tariff_type,
            fbs_list.next_tariff_charge,
            fbs_list.next_tariff_starts_at,
            fbs_list.next_tariff_charge_currency_code,
            row_number() OVER (PARTITION BY fbs_list.posting_number ORDER BY fbs_list.load_dttm DESC) AS rn
           FROM raw_ozon.fbs_list
        ), ft AS (
         SELECT ft_1.client_id,
            ft_1.operation_date,
            ft_1.posting_number,
            fti.sku,
            ft_1.accruals_for_sale
           FROM raw_ozon.finance_transaction ft_1
             LEFT JOIN raw_ozon.finance_transaction_items fti ON ft_1.operation_id = fti.operation_id
          WHERE fti.sku IS NOT NULL AND ft_1.operation_type = 'OperationAgentDeliveredToCustomer'::text
        ), fbo AS (
         SELECT l.client_id,
            l.created_at AS date,
            l.created_at AS completed_date,
            ft.operation_date,
            l.order_id,
            l.order_number,
            l.product_id,
            l.name,
            l.posting_number,
            'FBO'::text AS tpl_provider,
            l.sku,
            l.offer_id,
            l.quantity AS qty,
            ft.accruals_for_sale::numeric AS accruals_for_sale,
            ft.accruals_for_sale::numeric * l.quantity::numeric AS total_accruals_for_sale,
            l.payout::numeric AS payout,
            l.payout::numeric * l.quantity::numeric AS total_payout,
            l.price::numeric AS price,
            l.old_price::numeric AS old_price,
            l.payment_type_group_name,
            l.status,
                CASE
                    WHEN r.return_date IS NOT NULL THEN true
                    ELSE false
                END AS is_return,
            r.return_date::date AS return_date
           FROM pre_fbo l
             LEFT JOIN raw_ozon.returns_list r ON r.sku = l.sku AND r.order_number::text = l.order_number AND r.posting_number = l.posting_number AND r.place_id <> 0
             LEFT JOIN ft ON ft.posting_number = l.posting_number and ft.sku::numeric = l.sku
          WHERE l.rn = 1
          ORDER BY (l.created_at::date) DESC
        ), fbs AS (
         SELECT l.client_id,
            l.in_process_at::date AS date,
            l.delivering_date AS completed_date,
            ft.operation_date,
            l.order_id,
            l.order_number,
            l.product_id,
            l.name,
            l.posting_number,
                CASE
                    WHEN l.tpl_provider = 'Самостоятельно'::text THEN 'rFBS'::text
                    ELSE 'FBS'::text
                END AS tpl_provider,
            l.sku,
            l.offer_id,
            l.quantity AS qty,
            ft.accruals_for_sale::numeric AS accruals_for_sale,
            ft.accruals_for_sale::numeric * l.quantity::numeric AS total_accruals_for_sale,
            l.payout::numeric AS payout,
            l.payout::numeric * l.quantity::numeric AS total_payout,
            l.price::numeric AS price,
            l.old_price::numeric AS old_price,
            l.payment_type_group_name,
            l.status,
                CASE
                    WHEN r.return_date IS NOT NULL THEN true
                    ELSE false
                END AS is_return,
            r.return_date::date AS return_date
           FROM pre_fbs l
             LEFT JOIN raw_ozon.returns_list r ON r.sku = l.sku AND r.order_number::text = l.order_number AND r.posting_number = l.posting_number AND r.place_id <> 0
             LEFT JOIN ft ON ft.posting_number = l.posting_number and ft.sku::numeric = l.sku
          WHERE l.rn = 1
          ORDER BY (l.in_process_at::date) DESC
        )
 SELECT final_report.client_id,
    final_report.date,
    final_report.completed_date,
    final_report.operation_date,
    final_report.order_id,
    final_report.order_number,
    final_report.product_id,
    final_report.name,
    final_report.posting_number,
    final_report.tpl_provider,
    final_report.sku,
    final_report.offer_id,
    sum(final_report.qty) AS qty,
    final_report.accruals_for_sale,
    final_report.total_accruals_for_sale,
    final_report.payout,
    final_report.total_payout,
    final_report.price,
    final_report.old_price,
    final_report.payment_type_group_name,
    final_report.status,
    final_report.is_return,
    final_report.return_date
   FROM ( SELECT fbo.client_id,
            fbo.date,
            fbo.completed_date,
            fbo.operation_date,
            fbo.order_id,
            fbo.order_number,
            fbo.product_id,
            fbo.name,
            fbo.posting_number,
            fbo.tpl_provider,
            fbo.sku,
            fbo.offer_id,
            fbo.qty,
            fbo.accruals_for_sale,
            fbo.total_accruals_for_sale,
            fbo.payout,
            fbo.total_payout,
            fbo.price,
            fbo.old_price,
            fbo.payment_type_group_name,
            fbo.status,
            fbo.is_return,
            fbo.return_date
           FROM fbo
        UNION ALL
         SELECT fbs.client_id,
            fbs.date,
            fbs.completed_date,
            fbs.operation_date,
            fbs.order_id::text AS order_id,
            fbs.order_number,
            fbs.product_id,
            fbs.name,
            fbs.posting_number,
            fbs.tpl_provider,
            fbs.sku,
            fbs.offer_id,
            fbs.qty,
            fbs.accruals_for_sale,
            fbs.total_accruals_for_sale,
            fbs.payout,
            fbs.total_payout,
            fbs.price,
            fbs.old_price,
            fbs.payment_type_group_name,
            fbs.status,
            fbs.is_return,
            fbs.return_date
           FROM fbs) final_report
  WHERE final_report.status <> 'cancelled'::text
  GROUP BY final_report.date, final_report.price, final_report.order_id, final_report.client_id, final_report.sku, final_report.offer_id, final_report.payout, final_report.total_payout, final_report.status, final_report.is_return, final_report.return_date, final_report.order_number, final_report.product_id, final_report.name, final_report.posting_number, final_report.tpl_provider, final_report.old_price, final_report.payment_type_group_name, final_report.completed_date, final_report.operation_date, final_report.accruals_for_sale, final_report.total_accruals_for_sale
  ORDER BY final_report.date;